### ISSUE TITLE
Circular references in the storage cache when using observeOpenAI

### ISSUE THREAD

**Issue by pabloromeo** [langfuse/langfuse-js#217]
## Bug description

So, I've been using traces successfully within an application, all traces and spans get stored correctly and it works great.
However, I recently added the langfuse error handler and started logging errors from it, and noticed that every time traces occur I see the following errors being logged:

```
2024-05-23 22:26:31 Error while flushing Langfuse TypeError: Converting circular structure to JSON
2024-05-23 22:26:31     --> starting at object with constructor 'Object'
2024-05-23 22:26:31     |     property 'queue' -> object with constructor 'Array'
2024-05-23 22:26:31     |     index 2 -> object with constructor 'Object'
2024-05-23 22:26:31     |     ...
2024-05-23 22:26:31     |     property 'client' -> object with constructor 'Langfuse'
2024-05-23 22:26:31     --- property '_storageCache' closes the circle
2024-05-23 22:26:31     at JSON.stringify (<anonymous>)
2024-05-23 22:26:31     at Langfuse.setPersistedProperty (file:///usr/src/app/node_modules/langfuse/lib/index.mjs:177:50)
2024-05-23 22:26:31     at Langfuse.flush (file:///usr/src/app/node_modules/langfuse-core/lib/index.mjs:598:10)
2024-05-23 22:26:31     at file:///usr/src/app/node_modules/langfuse-core/lib/index.mjs:574:14
2024-05-23 22:26:31     at new Promise (<anonymous>)
2024-05-23 22:26:31     at Langfuse.flushAsync (file:///usr/src/app/node_modules/langfuse-core/lib/index.mjs:572:12)
```

I don't see what I might be doing wrong that is causing a circular reference to end up in the storage cache, since I'm just either manually creating a trace or a span just with a name and some input and output (which get shown correctly in langfuse), plus the `observeOpenAI` wrapper for OpenAI completions.

## How to reproduce

Traces that are manually created don't trigger the error, neither do spans.
The error appears as soon as it's a Generation automatically created by the `observeOpenAI` wrapped openAI client.

## Related sub-libraries

- [ ] All of them
- [X ] langfuse
- [ ] langfuse-node

## Additional context

Completions in my case are mostly done as streams. Not sure if that info helps. Even completions with tools, since I'm running an Agent with tools with streamed responses.
I'm using langfuse version 3.11.1 from npm.

**Comment by pabloromeo** [comment]
I've just noticed that once this error starts occurring it appears that future traces stop working, so the issues seems more serious than i initially thought. Any idea what might be going here?
